projectGroup=io.github.bluetape4k.text
baseVersion=0.1.3
snapshotVersion=

# Gradle JVM args
org.gradle.jvmargs=-Xms512M -Xmx4G -XX:+UseZGC -XX:+ZGenerational -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
org.gradle.caching=true

kotlin.incremental=true
kotlin.daemon.jvm.options=-Xmx2G -XX:+UseZGC

# Publishing
centralSnapshotsParallelism=4

# Shared bluetape4k ecosystem catalog version
